<?php

use Drupal\webform\WebformSubmissionInterface;




function conference_webform_submission_update(WebformSubmissionInterface $entity){
  $user_id = $entity->getOwnerId();
  $participants = $entity->getSourceEntity()->field_participants_du_programme->getValue();
  $data = $entity->getData();
  //ksm($data);
  //ajoute le participant à la Conférence
  if($data['adhesion'] == 'acceptee' && !in_array(['target_id'=> $user_id], $participants)) {
    $entity->getSourceEntity()->field_participants_du_programme->setValue(
      array_merge($participants, ['target_id'=> $user_id])
    );
    $entity->getSourceEntity()->save();
  }

  // supprime le participant à la Conférence
  if($data['adhesion'] != 'acceptee' && in_array(['target_id'=> $user_id], $participants)) {
    $key_data = array_search(['target_id'=> $user_id], $participants);
    unset($participants[$key_data]);
    $entity->getSourceEntity()->field_participants_du_programme->setValue($participants);
    $entity->getSourceEntity()->save();
  }
  //ksm($participants);
}